version: '3.8'

services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
  
  fastapi-server:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
